// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File_Type int32

const (
	File_OTHER File_Type = 0
	File_DOC   File_Type = 1
	File_PDF   File_Type = 2
	File_TXT   File_Type = 3
	File_EXCEL File_Type = 4
	File_IMAGE File_Type = 5
)

var File_Type_name = map[int32]string{
	0: "OTHER",
	1: "DOC",
	2: "PDF",
	3: "TXT",
	4: "EXCEL",
	5: "IMAGE",
}

var File_Type_value = map[string]int32{
	"OTHER": 0,
	"DOC":   1,
	"PDF":   2,
	"TXT":   3,
	"EXCEL": 4,
	"IMAGE": 5,
}

func (x File_Type) String() string {
	return proto.EnumName(File_Type_name, int32(x))
}

func (File_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3, 0}
}

type Folder struct {
	ParentIdentifier     string   `protobuf:"bytes,1,opt,name=parent_identifier,json=parentIdentifier,proto3" json:"parent_identifier,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier           string   `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CreationDate         string   `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Folder) Reset()         { *m = Folder{} }
func (m *Folder) String() string { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()    {}
func (*Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Folder.Unmarshal(m, b)
}
func (m *Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Folder.Marshal(b, m, deterministic)
}
func (m *Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Folder.Merge(m, src)
}
func (m *Folder) XXX_Size() int {
	return xxx_messageInfo_Folder.Size(m)
}
func (m *Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_Folder.DiscardUnknown(m)
}

var xxx_messageInfo_Folder proto.InternalMessageInfo

func (m *Folder) GetParentIdentifier() string {
	if m != nil {
		return m.ParentIdentifier
	}
	return ""
}

func (m *Folder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Folder) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Folder) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

type FSLevel struct {
	Folder               *Folder   `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Folders              []*Folder `protobuf:"bytes,2,rep,name=folders,proto3" json:"folders,omitempty"`
	Files                []*File   `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FSLevel) Reset()         { *m = FSLevel{} }
func (m *FSLevel) String() string { return proto.CompactTextString(m) }
func (*FSLevel) ProtoMessage()    {}
func (*FSLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *FSLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSLevel.Unmarshal(m, b)
}
func (m *FSLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSLevel.Marshal(b, m, deterministic)
}
func (m *FSLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSLevel.Merge(m, src)
}
func (m *FSLevel) XXX_Size() int {
	return xxx_messageInfo_FSLevel.Size(m)
}
func (m *FSLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_FSLevel.DiscardUnknown(m)
}

var xxx_messageInfo_FSLevel proto.InternalMessageInfo

func (m *FSLevel) GetFolder() *Folder {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *FSLevel) GetFolders() []*Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

func (m *FSLevel) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type FSTree struct {
	Folder               *Folder    `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Children             []*FSLevel `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Files                []*File    `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FSTree) Reset()         { *m = FSTree{} }
func (m *FSTree) String() string { return proto.CompactTextString(m) }
func (*FSTree) ProtoMessage()    {}
func (*FSTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *FSTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSTree.Unmarshal(m, b)
}
func (m *FSTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSTree.Marshal(b, m, deterministic)
}
func (m *FSTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSTree.Merge(m, src)
}
func (m *FSTree) XXX_Size() int {
	return xxx_messageInfo_FSTree.Size(m)
}
func (m *FSTree) XXX_DiscardUnknown() {
	xxx_messageInfo_FSTree.DiscardUnknown(m)
}

var xxx_messageInfo_FSTree proto.InternalMessageInfo

func (m *FSTree) GetFolder() *Folder {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *FSTree) GetChildren() []*FSLevel {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *FSTree) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	ParentIdentifier     string    `protobuf:"bytes,1,opt,name=parent_identifier,json=parentIdentifier,proto3" json:"parent_identifier,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier           string    `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CreationDate         string    `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ContentIdentifier    []byte    `protobuf:"bytes,5,opt,name=content_identifier,json=contentIdentifier,proto3" json:"content_identifier,omitempty"`
	FileType             File_Type `protobuf:"varint,6,opt,name=file_type,json=fileType,proto3,enum=file_service.File_Type" json:"file_type,omitempty"`
	Writable             bool      `protobuf:"varint,7,opt,name=writable,proto3" json:"writable,omitempty"`
	Private              bool      `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetParentIdentifier() string {
	if m != nil {
		return m.ParentIdentifier
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *File) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *File) GetContentIdentifier() []byte {
	if m != nil {
		return m.ContentIdentifier
	}
	return nil
}

func (m *File) GetFileType() File_Type {
	if m != nil {
		return m.FileType
	}
	return File_OTHER
}

func (m *File) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *File) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type Content struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateDriveRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDriveRequest) Reset()         { *m = CreateDriveRequest{} }
func (m *CreateDriveRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDriveRequest) ProtoMessage()    {}
func (*CreateDriveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateDriveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDriveRequest.Unmarshal(m, b)
}
func (m *CreateDriveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDriveRequest.Marshal(b, m, deterministic)
}
func (m *CreateDriveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDriveRequest.Merge(m, src)
}
func (m *CreateDriveRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDriveRequest.Size(m)
}
func (m *CreateDriveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDriveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDriveRequest proto.InternalMessageInfo

func (m *CreateDriveRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateDriveResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDriveResponse) Reset()         { *m = CreateDriveResponse{} }
func (m *CreateDriveResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDriveResponse) ProtoMessage()    {}
func (*CreateDriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CreateDriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDriveResponse.Unmarshal(m, b)
}
func (m *CreateDriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDriveResponse.Marshal(b, m, deterministic)
}
func (m *CreateDriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDriveResponse.Merge(m, src)
}
func (m *CreateDriveResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDriveResponse.Size(m)
}
func (m *CreateDriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDriveResponse proto.InternalMessageInfo

func (m *CreateDriveResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateDriveResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type UploadFileRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

func (m *UploadFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *UploadFileRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *UploadFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type UploadFileResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileResponse) Reset()         { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()    {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResponse.Unmarshal(m, b)
}
func (m *UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResponse.Merge(m, src)
}
func (m *UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadFileResponse.Size(m)
}
func (m *UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResponse proto.InternalMessageInfo

func (m *UploadFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *UploadFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type CreateNewFileRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewFileRequest) Reset()         { *m = CreateNewFileRequest{} }
func (m *CreateNewFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewFileRequest) ProtoMessage()    {}
func (*CreateNewFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *CreateNewFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewFileRequest.Unmarshal(m, b)
}
func (m *CreateNewFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewFileRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewFileRequest.Merge(m, src)
}
func (m *CreateNewFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewFileRequest.Size(m)
}
func (m *CreateNewFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewFileRequest proto.InternalMessageInfo

func (m *CreateNewFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateNewFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CreateNewFileResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewFileResponse) Reset()         { *m = CreateNewFileResponse{} }
func (m *CreateNewFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNewFileResponse) ProtoMessage()    {}
func (*CreateNewFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *CreateNewFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewFileResponse.Unmarshal(m, b)
}
func (m *CreateNewFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateNewFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewFileResponse.Merge(m, src)
}
func (m *CreateNewFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNewFileResponse.Size(m)
}
func (m *CreateNewFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewFileResponse proto.InternalMessageInfo

func (m *CreateNewFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateNewFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type CreateNewFolderRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewFolderRequest) Reset()         { *m = CreateNewFolderRequest{} }
func (m *CreateNewFolderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewFolderRequest) ProtoMessage()    {}
func (*CreateNewFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *CreateNewFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewFolderRequest.Unmarshal(m, b)
}
func (m *CreateNewFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewFolderRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewFolderRequest.Merge(m, src)
}
func (m *CreateNewFolderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewFolderRequest.Size(m)
}
func (m *CreateNewFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewFolderRequest proto.InternalMessageInfo

func (m *CreateNewFolderRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateNewFolderRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CreateNewFolderResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewFolderResponse) Reset()         { *m = CreateNewFolderResponse{} }
func (m *CreateNewFolderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNewFolderResponse) ProtoMessage()    {}
func (*CreateNewFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *CreateNewFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewFolderResponse.Unmarshal(m, b)
}
func (m *CreateNewFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewFolderResponse.Marshal(b, m, deterministic)
}
func (m *CreateNewFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewFolderResponse.Merge(m, src)
}
func (m *CreateNewFolderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNewFolderResponse.Size(m)
}
func (m *CreateNewFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewFolderResponse proto.InternalMessageInfo

func (m *CreateNewFolderResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateNewFolderResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type DeleteFileRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DeleteFileResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *DeleteFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type RenameFileRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameFileRequest) Reset()         { *m = RenameFileRequest{} }
func (m *RenameFileRequest) String() string { return proto.CompactTextString(m) }
func (*RenameFileRequest) ProtoMessage()    {}
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *RenameFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameFileRequest.Unmarshal(m, b)
}
func (m *RenameFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameFileRequest.Marshal(b, m, deterministic)
}
func (m *RenameFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameFileRequest.Merge(m, src)
}
func (m *RenameFileRequest) XXX_Size() int {
	return xxx_messageInfo_RenameFileRequest.Size(m)
}
func (m *RenameFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameFileRequest proto.InternalMessageInfo

func (m *RenameFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RenameFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RenameFileResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameFileResponse) Reset()         { *m = RenameFileResponse{} }
func (m *RenameFileResponse) String() string { return proto.CompactTextString(m) }
func (*RenameFileResponse) ProtoMessage()    {}
func (*RenameFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *RenameFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameFileResponse.Unmarshal(m, b)
}
func (m *RenameFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameFileResponse.Marshal(b, m, deterministic)
}
func (m *RenameFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameFileResponse.Merge(m, src)
}
func (m *RenameFileResponse) XXX_Size() int {
	return xxx_messageInfo_RenameFileResponse.Size(m)
}
func (m *RenameFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameFileResponse proto.InternalMessageInfo

func (m *RenameFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *RenameFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type MoveFileRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveFileRequest) Reset()         { *m = MoveFileRequest{} }
func (m *MoveFileRequest) String() string { return proto.CompactTextString(m) }
func (*MoveFileRequest) ProtoMessage()    {}
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *MoveFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveFileRequest.Unmarshal(m, b)
}
func (m *MoveFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveFileRequest.Marshal(b, m, deterministic)
}
func (m *MoveFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveFileRequest.Merge(m, src)
}
func (m *MoveFileRequest) XXX_Size() int {
	return xxx_messageInfo_MoveFileRequest.Size(m)
}
func (m *MoveFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveFileRequest proto.InternalMessageInfo

func (m *MoveFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *MoveFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type MoveFileResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveFileResponse) Reset()         { *m = MoveFileResponse{} }
func (m *MoveFileResponse) String() string { return proto.CompactTextString(m) }
func (*MoveFileResponse) ProtoMessage()    {}
func (*MoveFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *MoveFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveFileResponse.Unmarshal(m, b)
}
func (m *MoveFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveFileResponse.Marshal(b, m, deterministic)
}
func (m *MoveFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveFileResponse.Merge(m, src)
}
func (m *MoveFileResponse) XXX_Size() int {
	return xxx_messageInfo_MoveFileResponse.Size(m)
}
func (m *MoveFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveFileResponse proto.InternalMessageInfo

func (m *MoveFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *MoveFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type GetFolderContentRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFolderContentRequest) Reset()         { *m = GetFolderContentRequest{} }
func (m *GetFolderContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetFolderContentRequest) ProtoMessage()    {}
func (*GetFolderContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *GetFolderContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderContentRequest.Unmarshal(m, b)
}
func (m *GetFolderContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderContentRequest.Marshal(b, m, deterministic)
}
func (m *GetFolderContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderContentRequest.Merge(m, src)
}
func (m *GetFolderContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetFolderContentRequest.Size(m)
}
func (m *GetFolderContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderContentRequest proto.InternalMessageInfo

func (m *GetFolderContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type GetFolderContentResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Content              *FSLevel `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFolderContentResponse) Reset()         { *m = GetFolderContentResponse{} }
func (m *GetFolderContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetFolderContentResponse) ProtoMessage()    {}
func (*GetFolderContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{20}
}

func (m *GetFolderContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderContentResponse.Unmarshal(m, b)
}
func (m *GetFolderContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderContentResponse.Marshal(b, m, deterministic)
}
func (m *GetFolderContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderContentResponse.Merge(m, src)
}
func (m *GetFolderContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetFolderContentResponse.Size(m)
}
func (m *GetFolderContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderContentResponse proto.InternalMessageInfo

func (m *GetFolderContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFolderContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFolderContentResponse) GetContent() *FSLevel {
	if m != nil {
		return m.Content
	}
	return nil
}

type GetFileContentRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileContentRequest) Reset()         { *m = GetFileContentRequest{} }
func (m *GetFileContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileContentRequest) ProtoMessage()    {}
func (*GetFileContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{21}
}

func (m *GetFileContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileContentRequest.Unmarshal(m, b)
}
func (m *GetFileContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileContentRequest.Marshal(b, m, deterministic)
}
func (m *GetFileContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileContentRequest.Merge(m, src)
}
func (m *GetFileContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileContentRequest.Size(m)
}
func (m *GetFileContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileContentRequest proto.InternalMessageInfo

func (m *GetFileContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type GetFileContentResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	File                 *File    `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileContentResponse) Reset()         { *m = GetFileContentResponse{} }
func (m *GetFileContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileContentResponse) ProtoMessage()    {}
func (*GetFileContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{22}
}

func (m *GetFileContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileContentResponse.Unmarshal(m, b)
}
func (m *GetFileContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileContentResponse.Marshal(b, m, deterministic)
}
func (m *GetFileContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileContentResponse.Merge(m, src)
}
func (m *GetFileContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileContentResponse.Size(m)
}
func (m *GetFileContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileContentResponse proto.InternalMessageInfo

func (m *GetFileContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFileContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFileContentResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetFileTreeRequest struct {
	RootIdentifier       string   `protobuf:"bytes,1,opt,name=root_identifier,json=rootIdentifier,proto3" json:"root_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileTreeRequest) Reset()         { *m = GetFileTreeRequest{} }
func (m *GetFileTreeRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileTreeRequest) ProtoMessage()    {}
func (*GetFileTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{23}
}

func (m *GetFileTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileTreeRequest.Unmarshal(m, b)
}
func (m *GetFileTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileTreeRequest.Marshal(b, m, deterministic)
}
func (m *GetFileTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileTreeRequest.Merge(m, src)
}
func (m *GetFileTreeRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileTreeRequest.Size(m)
}
func (m *GetFileTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileTreeRequest proto.InternalMessageInfo

func (m *GetFileTreeRequest) GetRootIdentifier() string {
	if m != nil {
		return m.RootIdentifier
	}
	return ""
}

type GetFileTreeResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Tree                 *FSTree  `protobuf:"bytes,3,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileTreeResponse) Reset()         { *m = GetFileTreeResponse{} }
func (m *GetFileTreeResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileTreeResponse) ProtoMessage()    {}
func (*GetFileTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{24}
}

func (m *GetFileTreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileTreeResponse.Unmarshal(m, b)
}
func (m *GetFileTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileTreeResponse.Marshal(b, m, deterministic)
}
func (m *GetFileTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileTreeResponse.Merge(m, src)
}
func (m *GetFileTreeResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileTreeResponse.Size(m)
}
func (m *GetFileTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileTreeResponse proto.InternalMessageInfo

func (m *GetFileTreeResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFileTreeResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFileTreeResponse) GetTree() *FSTree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type UpdateFileContentRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	NewContent           []byte   `protobuf:"bytes,2,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileContentRequest) Reset()         { *m = UpdateFileContentRequest{} }
func (m *UpdateFileContentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileContentRequest) ProtoMessage()    {}
func (*UpdateFileContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{25}
}

func (m *UpdateFileContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileContentRequest.Unmarshal(m, b)
}
func (m *UpdateFileContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileContentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileContentRequest.Merge(m, src)
}
func (m *UpdateFileContentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileContentRequest.Size(m)
}
func (m *UpdateFileContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileContentRequest proto.InternalMessageInfo

func (m *UpdateFileContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateFileContentRequest) GetNewContent() []byte {
	if m != nil {
		return m.NewContent
	}
	return nil
}

type UpdateFileContentResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileContentResponse) Reset()         { *m = UpdateFileContentResponse{} }
func (m *UpdateFileContentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFileContentResponse) ProtoMessage()    {}
func (*UpdateFileContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{26}
}

func (m *UpdateFileContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileContentResponse.Unmarshal(m, b)
}
func (m *UpdateFileContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileContentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFileContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileContentResponse.Merge(m, src)
}
func (m *UpdateFileContentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFileContentResponse.Size(m)
}
func (m *UpdateFileContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileContentResponse proto.InternalMessageInfo

func (m *UpdateFileContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *UpdateFileContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("file_service.File_Type", File_Type_name, File_Type_value)
	proto.RegisterType((*Folder)(nil), "file_service.Folder")
	proto.RegisterType((*FSLevel)(nil), "file_service.FSLevel")
	proto.RegisterType((*FSTree)(nil), "file_service.FSTree")
	proto.RegisterType((*File)(nil), "file_service.File")
	proto.RegisterType((*Content)(nil), "file_service.Content")
	proto.RegisterType((*CreateDriveRequest)(nil), "file_service.CreateDriveRequest")
	proto.RegisterType((*CreateDriveResponse)(nil), "file_service.CreateDriveResponse")
	proto.RegisterType((*UploadFileRequest)(nil), "file_service.UploadFileRequest")
	proto.RegisterType((*UploadFileResponse)(nil), "file_service.UploadFileResponse")
	proto.RegisterType((*CreateNewFileRequest)(nil), "file_service.CreateNewFileRequest")
	proto.RegisterType((*CreateNewFileResponse)(nil), "file_service.CreateNewFileResponse")
	proto.RegisterType((*CreateNewFolderRequest)(nil), "file_service.CreateNewFolderRequest")
	proto.RegisterType((*CreateNewFolderResponse)(nil), "file_service.CreateNewFolderResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "file_service.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "file_service.DeleteFileResponse")
	proto.RegisterType((*RenameFileRequest)(nil), "file_service.RenameFileRequest")
	proto.RegisterType((*RenameFileResponse)(nil), "file_service.RenameFileResponse")
	proto.RegisterType((*MoveFileRequest)(nil), "file_service.MoveFileRequest")
	proto.RegisterType((*MoveFileResponse)(nil), "file_service.MoveFileResponse")
	proto.RegisterType((*GetFolderContentRequest)(nil), "file_service.GetFolderContentRequest")
	proto.RegisterType((*GetFolderContentResponse)(nil), "file_service.GetFolderContentResponse")
	proto.RegisterType((*GetFileContentRequest)(nil), "file_service.GetFileContentRequest")
	proto.RegisterType((*GetFileContentResponse)(nil), "file_service.GetFileContentResponse")
	proto.RegisterType((*GetFileTreeRequest)(nil), "file_service.GetFileTreeRequest")
	proto.RegisterType((*GetFileTreeResponse)(nil), "file_service.GetFileTreeResponse")
	proto.RegisterType((*UpdateFileContentRequest)(nil), "file_service.UpdateFileContentRequest")
	proto.RegisterType((*UpdateFileContentResponse)(nil), "file_service.UpdateFileContentResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x75, 0xa3, 0x3c, 0x92, 0x6d, 0x6a, 0x12, 0xc7, 0xac, 0x80, 0x36, 0x2a, 0x9d, 0x26,
	0x2a, 0xda, 0xa8, 0xa8, 0x53, 0xa0, 0xe8, 0x43, 0x1e, 0x1a, 0xc9, 0x76, 0x0d, 0x44, 0x4d, 0x4b,
	0x2b, 0x40, 0x90, 0xa2, 0x50, 0x28, 0x71, 0xec, 0x12, 0xa5, 0x49, 0x96, 0x64, 0x64, 0xe4, 0x27,
	0x7a, 0x41, 0x1f, 0xfb, 0x89, 0x05, 0xfa, 0x0d, 0xc5, 0x2e, 0x2f, 0xa2, 0x96, 0x92, 0x15, 0x15,
	0x25, 0x90, 0xb7, 0xe5, 0xec, 0x99, 0xd9, 0x73, 0x76, 0x67, 0x77, 0x86, 0xb0, 0x13, 0x90, 0x3f,
	0xb3, 0xa6, 0xd4, 0xf3, 0x7c, 0x37, 0x74, 0xb1, 0x79, 0x61, 0xd9, 0x34, 0x8e, 0x6d, 0xda, 0xaf,
	0x12, 0xd4, 0x4e, 0x5c, 0xdb, 0x24, 0x1f, 0x3f, 0x81, 0x96, 0x67, 0xf8, 0xe4, 0x84, 0x63, 0xcb,
	0x24, 0x27, 0xb4, 0x2e, 0x2c, 0xf2, 0x55, 0xa9, 0x23, 0x75, 0xb7, 0x75, 0x25, 0x9a, 0x38, 0x4b,
	0xed, 0x88, 0x50, 0x71, 0x8c, 0x2b, 0x52, 0x4b, 0x7c, 0x9e, 0x8f, 0xf1, 0x03, 0x80, 0x8c, 0x67,
	0x99, 0xcf, 0x64, 0x2c, 0x78, 0x08, 0x3b, 0x53, 0x9f, 0x8c, 0xd0, 0x72, 0x9d, 0xb1, 0x69, 0x84,
	0xa4, 0x56, 0x38, 0xa4, 0x99, 0x18, 0x07, 0x46, 0x48, 0xda, 0x1f, 0x12, 0xc8, 0x27, 0xe7, 0x4f,
	0x69, 0x46, 0x36, 0x7e, 0x0a, 0xb5, 0x0b, 0xce, 0x8d, 0xd3, 0x68, 0x1c, 0xdd, 0xee, 0x65, 0xb9,
	0xf7, 0x22, 0xde, 0x7a, 0x8c, 0xc1, 0x1e, 0xc8, 0xd1, 0x28, 0x50, 0x4b, 0x9d, 0xf2, 0x4a, 0x78,
	0x02, 0xc2, 0x2e, 0x54, 0xd9, 0x7c, 0xa0, 0x96, 0x39, 0x1a, 0x05, 0xb4, 0x65, 0x93, 0x1e, 0x01,
	0xb4, 0x3f, 0xd9, 0x26, 0x9d, 0x8f, 0x7c, 0xa2, 0x0d, 0x29, 0x7d, 0x0e, 0xf5, 0xe9, 0x4f, 0x96,
	0x6d, 0xfa, 0xe4, 0xc4, 0x9c, 0xf6, 0x05, 0x7c, 0xa4, 0x54, 0x4f, 0x61, 0x1b, 0xb0, 0xfa, 0xbb,
	0x04, 0x15, 0xf6, 0xfd, 0x6e, 0x1c, 0x1c, 0x3e, 0x04, 0x9c, 0xba, 0x4e, 0x28, 0xd0, 0xa8, 0x76,
	0xa4, 0x6e, 0x53, 0x6f, 0xc5, 0x33, 0x19, 0x1e, 0x5f, 0xc0, 0x36, 0x57, 0x16, 0xbe, 0xf1, 0x48,
	0xad, 0x75, 0xa4, 0xee, 0xee, 0xd1, 0x41, 0x5e, 0x6b, 0x6f, 0xf4, 0xc6, 0x23, 0xbd, 0xce, 0xec,
	0x6c, 0x84, 0x6d, 0xa8, 0x5f, 0xfb, 0x56, 0x68, 0x4c, 0x6c, 0x52, 0xe5, 0x8e, 0xd4, 0xad, 0xeb,
	0xe9, 0x37, 0xaa, 0x20, 0x7b, 0xbe, 0x35, 0x63, 0xfc, 0xea, 0x7c, 0x2a, 0xf9, 0xd4, 0x9e, 0x40,
	0x85, 0x7b, 0x6f, 0x43, 0xf5, 0xd9, 0xe8, 0x9b, 0x63, 0x5d, 0xd9, 0x42, 0x19, 0xca, 0x83, 0x67,
	0x7d, 0x45, 0x62, 0x83, 0xef, 0x06, 0x27, 0x4a, 0x89, 0x0d, 0x46, 0x2f, 0x46, 0x4a, 0x99, 0xa1,
	0x8e, 0x5f, 0xf4, 0x8f, 0x9f, 0x2a, 0x15, 0x36, 0x3c, 0x1b, 0x7e, 0x7d, 0x7a, 0xac, 0x54, 0xb5,
	0xc7, 0x20, 0xf7, 0x23, 0x11, 0xc2, 0x76, 0x49, 0xb9, 0xed, 0x42, 0xa8, 0x98, 0x46, 0x68, 0xf0,
	0x2d, 0x6e, 0xea, 0x7c, 0xac, 0x3d, 0x04, 0xec, 0xb3, 0xdd, 0xa2, 0x81, 0x6f, 0xcd, 0x48, 0xa7,
	0x5f, 0x5e, 0x53, 0x10, 0xe2, 0x01, 0xc8, 0xaf, 0x03, 0xf2, 0xc7, 0x96, 0x19, 0x87, 0xa9, 0xb1,
	0xcf, 0x33, 0x53, 0x23, 0xb8, 0xb5, 0x00, 0x0f, 0x3c, 0xd7, 0x09, 0x88, 0x1d, 0x84, 0x1f, 0x8f,
	0xc7, 0x53, 0xd7, 0x24, 0xee, 0x55, 0xd5, 0x9b, 0x89, 0xb1, 0xef, 0x9a, 0x84, 0x1f, 0x83, 0x92,
	0x82, 0xae, 0x28, 0x08, 0x8c, 0xcb, 0xe4, 0xb4, 0xf7, 0x12, 0xfb, 0x30, 0x32, 0xb3, 0xdb, 0xdf,
	0x7a, 0xee, 0xd9, 0xae, 0x61, 0xf2, 0xc4, 0x8a, 0x59, 0xdd, 0x87, 0x0a, 0xdb, 0xf0, 0x38, 0xc3,
	0x97, 0x65, 0x20, 0x9f, 0xc7, 0xcf, 0x40, 0x8e, 0xcf, 0x95, 0xc7, 0xcf, 0x25, 0x77, 0xbc, 0x5f,
	0x7a, 0x82, 0xc2, 0x0e, 0x34, 0x4c, 0x0a, 0x42, 0xcb, 0xe1, 0x59, 0x13, 0x27, 0x5a, 0xd6, 0xa4,
	0x99, 0x80, 0x59, 0x3e, 0x05, 0xc9, 0x7e, 0x05, 0xb7, 0xa3, 0xdd, 0xfd, 0x96, 0xae, 0xff, 0x8b,
	0x70, 0x41, 0x47, 0x29, 0xaf, 0xe3, 0x12, 0xf6, 0x85, 0x15, 0x0a, 0x92, 0x32, 0x81, 0x3b, 0xf3,
	0x85, 0xa2, 0xc7, 0xe7, 0x7f, 0x17, 0x63, 0xc1, 0x41, 0x6e, 0x8d, 0x82, 0xe4, 0x3c, 0x82, 0xd6,
	0x80, 0x6c, 0x0a, 0x29, 0x7b, 0x2c, 0x6b, 0xee, 0x1b, 0x4b, 0x9a, 0xac, 0x53, 0x41, 0xd4, 0x4e,
	0xa1, 0xa5, 0x13, 0x7b, 0x2e, 0x37, 0xa0, 0xb6, 0xec, 0xb5, 0x65, 0x74, 0xb3, 0x81, 0x0a, 0xa2,
	0x7b, 0x0e, 0x7b, 0x43, 0x77, 0xb6, 0x11, 0xd9, 0xf5, 0x99, 0x30, 0x01, 0x65, 0x1e, 0xb4, 0x20,
	0xe2, 0x5f, 0xc1, 0xc1, 0x29, 0x85, 0x51, 0x9e, 0x25, 0x2f, 0xc8, 0x5b, 0x26, 0xc2, 0x5f, 0x12,
	0xa8, 0x79, 0xdf, 0x62, 0x78, 0x66, 0x5f, 0xbf, 0xf2, 0xb2, 0xd7, 0x2f, 0x29, 0xed, 0x09, 0x4a,
	0xfb, 0x12, 0xf6, 0x19, 0x39, 0xcb, 0xa6, 0x0d, 0x65, 0xfd, 0x2e, 0xc1, 0x1d, 0xd1, 0xb3, 0x20,
	0x51, 0xc9, 0xa3, 0x51, 0xbe, 0xf9, 0xd1, 0xd0, 0x1e, 0x03, 0xc6, 0x8c, 0x58, 0x57, 0x94, 0x08,
	0x79, 0x00, 0x7b, 0xbe, 0xeb, 0x2e, 0x69, 0x43, 0x76, 0x99, 0x79, 0x5e, 0xfc, 0xb5, 0xdf, 0x24,
	0xb8, 0xb5, 0xe0, 0x5f, 0x90, 0x9c, 0x2e, 0x54, 0x42, 0x9f, 0x12, 0x39, 0x62, 0xaf, 0xc6, 0x3b,
	0x3a, 0x9d, 0x23, 0xb4, 0x1f, 0x40, 0x7d, 0xee, 0xb1, 0xde, 0x66, 0xf3, 0xf3, 0xc1, 0xbb, 0xd0,
	0x70, 0xe8, 0x7a, 0x9c, 0xad, 0x85, 0x4d, 0x1d, 0x1c, 0xba, 0x8e, 0xe3, 0x68, 0x3f, 0xc3, 0x7b,
	0x4b, 0x82, 0x17, 0xa3, 0xf9, 0xe8, 0x1f, 0x19, 0x76, 0xd9, 0x3a, 0x43, 0xc3, 0x31, 0x2e, 0xe9,
	0x8a, 0xd5, 0xdd, 0x11, 0x34, 0x32, 0xdd, 0x04, 0x76, 0x84, 0x32, 0x9d, 0xeb, 0x4b, 0xda, 0x1f,
	0xde, 0x80, 0x88, 0x56, 0xd3, 0xb6, 0xf0, 0x25, 0xec, 0x2c, 0xd4, 0x38, 0xd4, 0x96, 0x79, 0x2d,
	0x96, 0xd8, 0xf6, 0xe1, 0x8d, 0x98, 0x34, 0xf6, 0x2b, 0xd8, 0x13, 0x4a, 0x0e, 0xde, 0x5b, 0xe5,
	0x99, 0xad, 0x7a, 0xed, 0x8f, 0xd6, 0xa0, 0xd2, 0x15, 0xa6, 0xa0, 0x88, 0x4f, 0x05, 0x0a, 0xce,
	0x2b, 0x9e, 0xa1, 0xf6, 0xfd, 0x75, 0xb0, 0x74, 0x91, 0x1f, 0x61, 0x77, 0xf1, 0xe2, 0xe2, 0x61,
	0xde, 0x37, 0x97, 0x70, 0xed, 0x7b, 0x37, 0x83, 0xd2, 0xf0, 0x23, 0x68, 0x64, 0x6e, 0x91, 0x78,
	0xae, 0xf9, 0x0b, 0x2a, 0x9e, 0xeb, 0x92, 0x2b, 0xa8, 0x6d, 0xe1, 0x05, 0xeb, 0x09, 0x85, 0x6c,
	0x45, 0x41, 0xf3, 0xaa, 0xbb, 0xd2, 0x7e, 0xb0, 0x16, 0x97, 0xae, 0xf3, 0x3d, 0xc0, 0xbc, 0x6c,
	0xe3, 0xdd, 0x45, 0xc7, 0x5c, 0x17, 0xd0, 0xee, 0xac, 0x06, 0x64, 0x43, 0xce, 0x4b, 0xab, 0x18,
	0x32, 0x57, 0xbd, 0xc5, 0x90, 0xf9, 0xaa, 0xac, 0x6d, 0xe1, 0x10, 0xea, 0x49, 0xc9, 0xc3, 0xf7,
	0x17, 0xf1, 0x42, 0x7d, 0x15, 0xc3, 0xe5, 0x1b, 0xd9, 0x88, 0xe1, 0xdc, 0x2e, 0x32, 0xcc, 0xb5,
	0xe2, 0x6f, 0x13, 0xf2, 0x49, 0xe5, 0x65, 0xc9, 0x9b, 0x4c, 0x6a, 0xfc, 0xef, 0xfe, 0xd1, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x38, 0x4f, 0x8e, 0xee, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileManagementClient is the client API for FileManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileManagementClient interface {
	CreateDrive(ctx context.Context, in *CreateDriveRequest, opts ...grpc.CallOption) (*CreateDriveResponse, error)
	CreateNewFile(ctx context.Context, in *CreateNewFileRequest, opts ...grpc.CallOption) (*CreateNewFileResponse, error)
	CreateNewFolder(ctx context.Context, in *CreateNewFolderRequest, opts ...grpc.CallOption) (*CreateNewFolderResponse, error)
	GetFolderContent(ctx context.Context, in *GetFolderContentRequest, opts ...grpc.CallOption) (*GetFolderContentResponse, error)
	GetFileContent(ctx context.Context, in *GetFileContentRequest, opts ...grpc.CallOption) (*GetFileContentResponse, error)
	GetFileTree(ctx context.Context, in *GetFileTreeRequest, opts ...grpc.CallOption) (*GetFileTreeResponse, error)
	UpdateFileContent(ctx context.Context, in *UpdateFileContentRequest, opts ...grpc.CallOption) (*UpdateFileContentResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
}

type fileManagementClient struct {
	cc *grpc.ClientConn
}

func NewFileManagementClient(cc *grpc.ClientConn) FileManagementClient {
	return &fileManagementClient{cc}
}

func (c *fileManagementClient) CreateDrive(ctx context.Context, in *CreateDriveRequest, opts ...grpc.CallOption) (*CreateDriveResponse, error) {
	out := new(CreateDriveResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/CreateDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) CreateNewFile(ctx context.Context, in *CreateNewFileRequest, opts ...grpc.CallOption) (*CreateNewFileResponse, error) {
	out := new(CreateNewFileResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/CreateNewFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) CreateNewFolder(ctx context.Context, in *CreateNewFolderRequest, opts ...grpc.CallOption) (*CreateNewFolderResponse, error) {
	out := new(CreateNewFolderResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/CreateNewFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFolderContent(ctx context.Context, in *GetFolderContentRequest, opts ...grpc.CallOption) (*GetFolderContentResponse, error) {
	out := new(GetFolderContentResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/GetFolderContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFileContent(ctx context.Context, in *GetFileContentRequest, opts ...grpc.CallOption) (*GetFileContentResponse, error) {
	out := new(GetFileContentResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/GetFileContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFileTree(ctx context.Context, in *GetFileTreeRequest, opts ...grpc.CallOption) (*GetFileTreeResponse, error) {
	out := new(GetFileTreeResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/GetFileTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) UpdateFileContent(ctx context.Context, in *UpdateFileContentRequest, opts ...grpc.CallOption) (*UpdateFileContentResponse, error) {
	out := new(UpdateFileContentResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/UpdateFileContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/RenameFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/MoveFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, "/file_service.FileManagement/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileManagementServer is the server API for FileManagement service.
type FileManagementServer interface {
	CreateDrive(context.Context, *CreateDriveRequest) (*CreateDriveResponse, error)
	CreateNewFile(context.Context, *CreateNewFileRequest) (*CreateNewFileResponse, error)
	CreateNewFolder(context.Context, *CreateNewFolderRequest) (*CreateNewFolderResponse, error)
	GetFolderContent(context.Context, *GetFolderContentRequest) (*GetFolderContentResponse, error)
	GetFileContent(context.Context, *GetFileContentRequest) (*GetFileContentResponse, error)
	GetFileTree(context.Context, *GetFileTreeRequest) (*GetFileTreeResponse, error)
	UpdateFileContent(context.Context, *UpdateFileContentRequest) (*UpdateFileContentResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	MoveFile(context.Context, *MoveFileRequest) (*UploadFileResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
}

func RegisterFileManagementServer(s *grpc.Server, srv FileManagementServer) {
	s.RegisterService(&_FileManagement_serviceDesc, srv)
}

func _FileManagement_CreateDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateDrive(ctx, req.(*CreateDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_CreateNewFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateNewFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateNewFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateNewFile(ctx, req.(*CreateNewFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_CreateNewFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateNewFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateNewFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateNewFolder(ctx, req.(*CreateNewFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFolderContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFolderContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFolderContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFolderContent(ctx, req.(*GetFolderContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFileContent(ctx, req.(*GetFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFileTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFileTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFileTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFileTree(ctx, req.(*GetFileTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_UpdateFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).UpdateFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/UpdateFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).UpdateFileContent(ctx, req.(*UpdateFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/RenameFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/MoveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "file_service.FileManagement",
	HandlerType: (*FileManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDrive",
			Handler:    _FileManagement_CreateDrive_Handler,
		},
		{
			MethodName: "CreateNewFile",
			Handler:    _FileManagement_CreateNewFile_Handler,
		},
		{
			MethodName: "CreateNewFolder",
			Handler:    _FileManagement_CreateNewFolder_Handler,
		},
		{
			MethodName: "GetFolderContent",
			Handler:    _FileManagement_GetFolderContent_Handler,
		},
		{
			MethodName: "GetFileContent",
			Handler:    _FileManagement_GetFileContent_Handler,
		},
		{
			MethodName: "GetFileTree",
			Handler:    _FileManagement_GetFileTree_Handler,
		},
		{
			MethodName: "UpdateFileContent",
			Handler:    _FileManagement_UpdateFileContent_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileManagement_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileManagement_RenameFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _FileManagement_MoveFile_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _FileManagement_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
