// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Folder
	FSLevel
	FSTree
	File
	CreateDriveRequest
	CreateDriveResponse
	UploadFileRequest
	UploadFileResponse
	CreateNewFileRequest
	CreateNewFileResponse
	CreateNewFolderRequest
	CreateNewFolderResponse
	DeleteFileRequest
	DeleteFileResponse
	RenameFileRequest
	RenameFileResponse
	MoveFileRequest
	MoveFileResponse
	GetFolderContentRequest
	GetFolderContentResponse
	GetFileContentRequest
	GetFileContentResponse
	GetFileTreeRequest
	GetFileTreeResponse
	UpdateFileContentRequest
	UpdateFileContentResponse
	ShareFileRequest
	ShareFileResponse
	DownloadFileRequest
	DownloadFileResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File_Type int32

const (
	File_OTHER File_Type = 0
	File_DOC   File_Type = 1
	File_PDF   File_Type = 2
	File_TXT   File_Type = 3
	File_EXCEL File_Type = 4
	File_IMAGE File_Type = 5
)

var File_Type_name = map[int32]string{
	0: "OTHER",
	1: "DOC",
	2: "PDF",
	3: "TXT",
	4: "EXCEL",
	5: "IMAGE",
}
var File_Type_value = map[string]int32{
	"OTHER": 0,
	"DOC":   1,
	"PDF":   2,
	"TXT":   3,
	"EXCEL": 4,
	"IMAGE": 5,
}

func (x File_Type) String() string {
	return proto.EnumName(File_Type_name, int32(x))
}
func (File_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Folder struct {
	ParentIdentifier string `protobuf:"bytes,1,opt,name=parent_identifier,json=parentIdentifier" json:"parent_identifier,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Identifier       string `protobuf:"bytes,3,opt,name=identifier" json:"identifier,omitempty"`
	CreationDate     string `protobuf:"bytes,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
}

func (m *Folder) Reset()                    { *m = Folder{} }
func (m *Folder) String() string            { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()               {}
func (*Folder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Folder) GetParentIdentifier() string {
	if m != nil {
		return m.ParentIdentifier
	}
	return ""
}

func (m *Folder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Folder) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Folder) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

type FSLevel struct {
	Folder  *Folder   `protobuf:"bytes,1,opt,name=folder" json:"folder,omitempty"`
	Folders []*Folder `protobuf:"bytes,2,rep,name=folders" json:"folders,omitempty"`
	Files   []*File   `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
}

func (m *FSLevel) Reset()                    { *m = FSLevel{} }
func (m *FSLevel) String() string            { return proto.CompactTextString(m) }
func (*FSLevel) ProtoMessage()               {}
func (*FSLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FSLevel) GetFolder() *Folder {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *FSLevel) GetFolders() []*Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

func (m *FSLevel) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type FSTree struct {
	Folder   *Folder    `protobuf:"bytes,1,opt,name=folder" json:"folder,omitempty"`
	Children []*FSLevel `protobuf:"bytes,2,rep,name=children" json:"children,omitempty"`
	Files    []*File    `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
}

func (m *FSTree) Reset()                    { *m = FSTree{} }
func (m *FSTree) String() string            { return proto.CompactTextString(m) }
func (*FSTree) ProtoMessage()               {}
func (*FSTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FSTree) GetFolder() *Folder {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *FSTree) GetChildren() []*FSLevel {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *FSTree) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	ParentIdentifier string    `protobuf:"bytes,1,opt,name=parent_identifier,json=parentIdentifier" json:"parent_identifier,omitempty"`
	Name             string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Identifier       string    `protobuf:"bytes,3,opt,name=identifier" json:"identifier,omitempty"`
	CreationDate     string    `protobuf:"bytes,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	FileType         File_Type `protobuf:"varint,6,opt,name=file_type,json=fileType,enum=file_service.File_Type" json:"file_type,omitempty"`
	Writable         bool      `protobuf:"varint,7,opt,name=writable" json:"writable,omitempty"`
	Private          bool      `protobuf:"varint,8,opt,name=private" json:"private,omitempty"`
	Content          []byte    `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *File) GetParentIdentifier() string {
	if m != nil {
		return m.ParentIdentifier
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *File) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *File) GetFileType() File_Type {
	if m != nil {
		return m.FileType
	}
	return File_OTHER
}

func (m *File) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *File) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type CreateDriveRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *CreateDriveRequest) Reset()                    { *m = CreateDriveRequest{} }
func (m *CreateDriveRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDriveRequest) ProtoMessage()               {}
func (*CreateDriveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateDriveRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateDriveResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	DriveId         string `protobuf:"bytes,3,opt,name=drive_id,json=driveId" json:"drive_id,omitempty"`
}

func (m *CreateDriveResponse) Reset()                    { *m = CreateDriveResponse{} }
func (m *CreateDriveResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDriveResponse) ProtoMessage()               {}
func (*CreateDriveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateDriveResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateDriveResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *CreateDriveResponse) GetDriveId() string {
	if m != nil {
		return m.DriveId
	}
	return ""
}

type UploadFileRequest struct {
	File        *File  `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Destination string `protobuf:"bytes,3,opt,name=destination" json:"destination,omitempty"`
}

func (m *UploadFileRequest) Reset()                    { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()               {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UploadFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *UploadFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type UploadFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	FileId          string `protobuf:"bytes,3,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *UploadFileResponse) Reset()                    { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()               {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UploadFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *UploadFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *UploadFileResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type CreateNewFileRequest struct {
	File        *File  `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *CreateNewFileRequest) Reset()                    { *m = CreateNewFileRequest{} }
func (m *CreateNewFileRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNewFileRequest) ProtoMessage()               {}
func (*CreateNewFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateNewFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateNewFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CreateNewFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	FileId          string `protobuf:"bytes,3,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *CreateNewFileResponse) Reset()                    { *m = CreateNewFileResponse{} }
func (m *CreateNewFileResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNewFileResponse) ProtoMessage()               {}
func (*CreateNewFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateNewFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateNewFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *CreateNewFileResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type CreateNewFolderRequest struct {
	File        *File  `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *CreateNewFolderRequest) Reset()                    { *m = CreateNewFolderRequest{} }
func (m *CreateNewFolderRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNewFolderRequest) ProtoMessage()               {}
func (*CreateNewFolderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateNewFolderRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateNewFolderRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CreateNewFolderResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	FileId          string `protobuf:"bytes,3,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *CreateNewFolderResponse) Reset()                    { *m = CreateNewFolderResponse{} }
func (m *CreateNewFolderResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNewFolderResponse) ProtoMessage()               {}
func (*CreateNewFolderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateNewFolderResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CreateNewFolderResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *CreateNewFolderResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type DeleteFileRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *DeleteFileRequest) Reset()                    { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()               {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DeleteFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
}

func (m *DeleteFileResponse) Reset()                    { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()               {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *DeleteFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type RenameFileRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RenameFileRequest) Reset()                    { *m = RenameFileRequest{} }
func (m *RenameFileRequest) String() string            { return proto.CompactTextString(m) }
func (*RenameFileRequest) ProtoMessage()               {}
func (*RenameFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RenameFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RenameFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RenameFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
}

func (m *RenameFileResponse) Reset()                    { *m = RenameFileResponse{} }
func (m *RenameFileResponse) String() string            { return proto.CompactTextString(m) }
func (*RenameFileResponse) ProtoMessage()               {}
func (*RenameFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RenameFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *RenameFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type MoveFileRequest struct {
	Identifier  string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *MoveFileRequest) Reset()                    { *m = MoveFileRequest{} }
func (m *MoveFileRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveFileRequest) ProtoMessage()               {}
func (*MoveFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MoveFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *MoveFileRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type MoveFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
}

func (m *MoveFileResponse) Reset()                    { *m = MoveFileResponse{} }
func (m *MoveFileResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveFileResponse) ProtoMessage()               {}
func (*MoveFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *MoveFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *MoveFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type GetFolderContentRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *GetFolderContentRequest) Reset()                    { *m = GetFolderContentRequest{} }
func (m *GetFolderContentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFolderContentRequest) ProtoMessage()               {}
func (*GetFolderContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetFolderContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type GetFolderContentResponse struct {
	ResponseCode    int32    `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string   `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	Content         *FSLevel `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *GetFolderContentResponse) Reset()                    { *m = GetFolderContentResponse{} }
func (m *GetFolderContentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFolderContentResponse) ProtoMessage()               {}
func (*GetFolderContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetFolderContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFolderContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFolderContentResponse) GetContent() *FSLevel {
	if m != nil {
		return m.Content
	}
	return nil
}

type GetFileContentRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *GetFileContentRequest) Reset()                    { *m = GetFileContentRequest{} }
func (m *GetFileContentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileContentRequest) ProtoMessage()               {}
func (*GetFileContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetFileContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type GetFileContentResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	File            *File  `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
}

func (m *GetFileContentResponse) Reset()                    { *m = GetFileContentResponse{} }
func (m *GetFileContentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileContentResponse) ProtoMessage()               {}
func (*GetFileContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetFileContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFileContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFileContentResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetFileTreeRequest struct {
	RootIdentifier string `protobuf:"bytes,1,opt,name=root_identifier,json=rootIdentifier" json:"root_identifier,omitempty"`
}

func (m *GetFileTreeRequest) Reset()                    { *m = GetFileTreeRequest{} }
func (m *GetFileTreeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileTreeRequest) ProtoMessage()               {}
func (*GetFileTreeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetFileTreeRequest) GetRootIdentifier() string {
	if m != nil {
		return m.RootIdentifier
	}
	return ""
}

type GetFileTreeResponse struct {
	ResponseCode    int32   `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string  `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	Tree            *FSTree `protobuf:"bytes,3,opt,name=tree" json:"tree,omitempty"`
}

func (m *GetFileTreeResponse) Reset()                    { *m = GetFileTreeResponse{} }
func (m *GetFileTreeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileTreeResponse) ProtoMessage()               {}
func (*GetFileTreeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetFileTreeResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetFileTreeResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *GetFileTreeResponse) GetTree() *FSTree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type UpdateFileContentRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	NewContent []byte `protobuf:"bytes,2,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
}

func (m *UpdateFileContentRequest) Reset()                    { *m = UpdateFileContentRequest{} }
func (m *UpdateFileContentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateFileContentRequest) ProtoMessage()               {}
func (*UpdateFileContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *UpdateFileContentRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateFileContentRequest) GetNewContent() []byte {
	if m != nil {
		return m.NewContent
	}
	return nil
}

type UpdateFileContentResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
}

func (m *UpdateFileContentResponse) Reset()                    { *m = UpdateFileContentResponse{} }
func (m *UpdateFileContentResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateFileContentResponse) ProtoMessage()               {}
func (*UpdateFileContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *UpdateFileContentResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *UpdateFileContentResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type ShareFileRequest struct {
	Identifier      string   `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	UserIdentifiers []string `protobuf:"bytes,2,rep,name=user_identifiers,json=userIdentifiers" json:"user_identifiers,omitempty"`
}

func (m *ShareFileRequest) Reset()                    { *m = ShareFileRequest{} }
func (m *ShareFileRequest) String() string            { return proto.CompactTextString(m) }
func (*ShareFileRequest) ProtoMessage()               {}
func (*ShareFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ShareFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ShareFileRequest) GetUserIdentifiers() []string {
	if m != nil {
		return m.UserIdentifiers
	}
	return nil
}

type ShareFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
}

func (m *ShareFileResponse) Reset()                    { *m = ShareFileResponse{} }
func (m *ShareFileResponse) String() string            { return proto.CompactTextString(m) }
func (*ShareFileResponse) ProtoMessage()               {}
func (*ShareFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ShareFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *ShareFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type DownloadFileRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *DownloadFileRequest) Reset()                    { *m = DownloadFileRequest{} }
func (m *DownloadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*DownloadFileRequest) ProtoMessage()               {}
func (*DownloadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *DownloadFileRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DownloadFileResponse struct {
	ResponseCode    int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	ResponseMessage string `protobuf:"bytes,2,opt,name=response_message,json=responseMessage" json:"response_message,omitempty"`
	File            *File  `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
	Content         []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *DownloadFileResponse) Reset()                    { *m = DownloadFileResponse{} }
func (m *DownloadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*DownloadFileResponse) ProtoMessage()               {}
func (*DownloadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *DownloadFileResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *DownloadFileResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func (m *DownloadFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *DownloadFileResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Folder)(nil), "file_service.Folder")
	proto.RegisterType((*FSLevel)(nil), "file_service.FSLevel")
	proto.RegisterType((*FSTree)(nil), "file_service.FSTree")
	proto.RegisterType((*File)(nil), "file_service.File")
	proto.RegisterType((*CreateDriveRequest)(nil), "file_service.CreateDriveRequest")
	proto.RegisterType((*CreateDriveResponse)(nil), "file_service.CreateDriveResponse")
	proto.RegisterType((*UploadFileRequest)(nil), "file_service.UploadFileRequest")
	proto.RegisterType((*UploadFileResponse)(nil), "file_service.UploadFileResponse")
	proto.RegisterType((*CreateNewFileRequest)(nil), "file_service.CreateNewFileRequest")
	proto.RegisterType((*CreateNewFileResponse)(nil), "file_service.CreateNewFileResponse")
	proto.RegisterType((*CreateNewFolderRequest)(nil), "file_service.CreateNewFolderRequest")
	proto.RegisterType((*CreateNewFolderResponse)(nil), "file_service.CreateNewFolderResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "file_service.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "file_service.DeleteFileResponse")
	proto.RegisterType((*RenameFileRequest)(nil), "file_service.RenameFileRequest")
	proto.RegisterType((*RenameFileResponse)(nil), "file_service.RenameFileResponse")
	proto.RegisterType((*MoveFileRequest)(nil), "file_service.MoveFileRequest")
	proto.RegisterType((*MoveFileResponse)(nil), "file_service.MoveFileResponse")
	proto.RegisterType((*GetFolderContentRequest)(nil), "file_service.GetFolderContentRequest")
	proto.RegisterType((*GetFolderContentResponse)(nil), "file_service.GetFolderContentResponse")
	proto.RegisterType((*GetFileContentRequest)(nil), "file_service.GetFileContentRequest")
	proto.RegisterType((*GetFileContentResponse)(nil), "file_service.GetFileContentResponse")
	proto.RegisterType((*GetFileTreeRequest)(nil), "file_service.GetFileTreeRequest")
	proto.RegisterType((*GetFileTreeResponse)(nil), "file_service.GetFileTreeResponse")
	proto.RegisterType((*UpdateFileContentRequest)(nil), "file_service.UpdateFileContentRequest")
	proto.RegisterType((*UpdateFileContentResponse)(nil), "file_service.UpdateFileContentResponse")
	proto.RegisterType((*ShareFileRequest)(nil), "file_service.ShareFileRequest")
	proto.RegisterType((*ShareFileResponse)(nil), "file_service.ShareFileResponse")
	proto.RegisterType((*DownloadFileRequest)(nil), "file_service.DownloadFileRequest")
	proto.RegisterType((*DownloadFileResponse)(nil), "file_service.DownloadFileResponse")
	proto.RegisterEnum("file_service.File_Type", File_Type_name, File_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FileManagement service

type FileManagementClient interface {
	CreateDrive(ctx context.Context, in *CreateDriveRequest, opts ...grpc.CallOption) (*CreateDriveResponse, error)
	CreateNewFile(ctx context.Context, in *CreateNewFileRequest, opts ...grpc.CallOption) (*CreateNewFileResponse, error)
	CreateNewFolder(ctx context.Context, in *CreateNewFolderRequest, opts ...grpc.CallOption) (*CreateNewFolderResponse, error)
	GetFolderContent(ctx context.Context, in *GetFolderContentRequest, opts ...grpc.CallOption) (*GetFolderContentResponse, error)
	GetFileContent(ctx context.Context, in *GetFileContentRequest, opts ...grpc.CallOption) (*GetFileContentResponse, error)
	GetFileTree(ctx context.Context, in *GetFileTreeRequest, opts ...grpc.CallOption) (*GetFileTreeResponse, error)
	UpdateFileContent(ctx context.Context, in *UpdateFileContentRequest, opts ...grpc.CallOption) (*UpdateFileContentResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	ShareFile(ctx context.Context, in *ShareFileRequest, opts ...grpc.CallOption) (*ShareFileResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error)
}

type fileManagementClient struct {
	cc *grpc.ClientConn
}

func NewFileManagementClient(cc *grpc.ClientConn) FileManagementClient {
	return &fileManagementClient{cc}
}

func (c *fileManagementClient) CreateDrive(ctx context.Context, in *CreateDriveRequest, opts ...grpc.CallOption) (*CreateDriveResponse, error) {
	out := new(CreateDriveResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/CreateDrive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) CreateNewFile(ctx context.Context, in *CreateNewFileRequest, opts ...grpc.CallOption) (*CreateNewFileResponse, error) {
	out := new(CreateNewFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/CreateNewFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) CreateNewFolder(ctx context.Context, in *CreateNewFolderRequest, opts ...grpc.CallOption) (*CreateNewFolderResponse, error) {
	out := new(CreateNewFolderResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/CreateNewFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFolderContent(ctx context.Context, in *GetFolderContentRequest, opts ...grpc.CallOption) (*GetFolderContentResponse, error) {
	out := new(GetFolderContentResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/GetFolderContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFileContent(ctx context.Context, in *GetFileContentRequest, opts ...grpc.CallOption) (*GetFileContentResponse, error) {
	out := new(GetFileContentResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/GetFileContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) GetFileTree(ctx context.Context, in *GetFileTreeRequest, opts ...grpc.CallOption) (*GetFileTreeResponse, error) {
	out := new(GetFileTreeResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/GetFileTree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) UpdateFileContent(ctx context.Context, in *UpdateFileContentRequest, opts ...grpc.CallOption) (*UpdateFileContentResponse, error) {
	out := new(UpdateFileContentResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/UpdateFileContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/DeleteFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	out := new(RenameFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/RenameFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	out := new(UploadFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/MoveFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	out := new(UploadFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/UploadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) ShareFile(ctx context.Context, in *ShareFileRequest, opts ...grpc.CallOption) (*ShareFileResponse, error) {
	out := new(ShareFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/ShareFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagementClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error) {
	out := new(DownloadFileResponse)
	err := grpc.Invoke(ctx, "/file_service.FileManagement/DownloadFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileManagement service

type FileManagementServer interface {
	CreateDrive(context.Context, *CreateDriveRequest) (*CreateDriveResponse, error)
	CreateNewFile(context.Context, *CreateNewFileRequest) (*CreateNewFileResponse, error)
	CreateNewFolder(context.Context, *CreateNewFolderRequest) (*CreateNewFolderResponse, error)
	GetFolderContent(context.Context, *GetFolderContentRequest) (*GetFolderContentResponse, error)
	GetFileContent(context.Context, *GetFileContentRequest) (*GetFileContentResponse, error)
	GetFileTree(context.Context, *GetFileTreeRequest) (*GetFileTreeResponse, error)
	UpdateFileContent(context.Context, *UpdateFileContentRequest) (*UpdateFileContentResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	MoveFile(context.Context, *MoveFileRequest) (*UploadFileResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	ShareFile(context.Context, *ShareFileRequest) (*ShareFileResponse, error)
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error)
}

func RegisterFileManagementServer(s *grpc.Server, srv FileManagementServer) {
	s.RegisterService(&_FileManagement_serviceDesc, srv)
}

func _FileManagement_CreateDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateDrive(ctx, req.(*CreateDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_CreateNewFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateNewFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateNewFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateNewFile(ctx, req.(*CreateNewFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_CreateNewFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).CreateNewFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/CreateNewFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).CreateNewFolder(ctx, req.(*CreateNewFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFolderContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFolderContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFolderContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFolderContent(ctx, req.(*GetFolderContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFileContent(ctx, req.(*GetFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_GetFileTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).GetFileTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/GetFileTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).GetFileTree(ctx, req.(*GetFileTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_UpdateFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).UpdateFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/UpdateFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).UpdateFileContent(ctx, req.(*UpdateFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/RenameFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/MoveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_ShareFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).ShareFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/ShareFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).ShareFile(ctx, req.(*ShareFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagement_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagementServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FileManagement/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagementServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "file_service.FileManagement",
	HandlerType: (*FileManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDrive",
			Handler:    _FileManagement_CreateDrive_Handler,
		},
		{
			MethodName: "CreateNewFile",
			Handler:    _FileManagement_CreateNewFile_Handler,
		},
		{
			MethodName: "CreateNewFolder",
			Handler:    _FileManagement_CreateNewFolder_Handler,
		},
		{
			MethodName: "GetFolderContent",
			Handler:    _FileManagement_GetFolderContent_Handler,
		},
		{
			MethodName: "GetFileContent",
			Handler:    _FileManagement_GetFileContent_Handler,
		},
		{
			MethodName: "GetFileTree",
			Handler:    _FileManagement_GetFileTree_Handler,
		},
		{
			MethodName: "UpdateFileContent",
			Handler:    _FileManagement_UpdateFileContent_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileManagement_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileManagement_RenameFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _FileManagement_MoveFile_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _FileManagement_UploadFile_Handler,
		},
		{
			MethodName: "ShareFile",
			Handler:    _FileManagement_ShareFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _FileManagement_DownloadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0xfe, 0x51, 0x92, 0xf5, 0x67, 0xac, 0xd8, 0xf4, 0xda, 0x8e, 0x68, 0xfe, 0x1c, 0x5b, 0x5d,
	0x3b, 0x8e, 0x92, 0xb6, 0x16, 0xe2, 0xb4, 0x28, 0x1a, 0xa0, 0x87, 0xc6, 0xb2, 0x5d, 0x03, 0x71,
	0x53, 0xd0, 0x0e, 0x10, 0xb4, 0x08, 0x54, 0x5a, 0x1c, 0x3b, 0x44, 0x65, 0x52, 0x21, 0x69, 0x19,
	0x3e, 0xa4, 0x0d, 0x72, 0x68, 0x81, 0x1e, 0xfa, 0x07, 0x39, 0xf6, 0x05, 0xfa, 0x3e, 0x05, 0xfa,
	0x04, 0x3d, 0xf5, 0x29, 0x8a, 0x5d, 0x92, 0x12, 0xb9, 0xa4, 0x24, 0x0b, 0x88, 0xd2, 0xde, 0x76,
	0x67, 0xbf, 0x9d, 0xf9, 0x66, 0x77, 0x38, 0xfb, 0x49, 0x70, 0xcd, 0x45, 0xa7, 0x6b, 0xb6, 0x70,
	0xb3, 0xe3, 0xd8, 0x9e, 0x4d, 0xca, 0x27, 0x66, 0x1b, 0x9b, 0x81, 0x4d, 0x5d, 0x3e, 0xb5, 0xed,
	0xd3, 0x36, 0xd6, 0xf5, 0x8e, 0x59, 0xd7, 0x2d, 0xcb, 0xf6, 0x74, 0xcf, 0xb4, 0x2d, 0xd7, 0xc7,
	0xd2, 0x9f, 0x24, 0xc8, 0xef, 0xda, 0x6d, 0x03, 0x1d, 0xf2, 0x2e, 0xcc, 0x75, 0x74, 0x07, 0x2d,
	0xaf, 0x69, 0x1a, 0x68, 0x79, 0xe6, 0x89, 0x89, 0x8e, 0x22, 0x55, 0xa5, 0x5a, 0x49, 0x93, 0xfd,
	0x85, 0xfd, 0x9e, 0x9d, 0x10, 0xc8, 0x59, 0xfa, 0x19, 0x2a, 0x19, 0xbe, 0xce, 0xc7, 0x64, 0x05,
	0x20, 0xb2, 0x33, 0xcb, 0x57, 0x22, 0x16, 0xb2, 0x06, 0xd7, 0x5a, 0x0e, 0xf2, 0xf0, 0x4d, 0x43,
	0xf7, 0x50, 0xc9, 0x71, 0x48, 0x39, 0x34, 0x36, 0x74, 0x0f, 0xe9, 0xaf, 0x12, 0x14, 0x76, 0x0f,
	0x1f, 0x62, 0x17, 0xdb, 0xe4, 0x3d, 0xc8, 0x9f, 0x70, 0x6e, 0x9c, 0xc6, 0xf4, 0xd6, 0xc2, 0x66,
	0x34, 0xb3, 0x4d, 0x9f, 0xb7, 0x16, 0x60, 0xc8, 0x26, 0x14, 0xfc, 0x91, 0xab, 0x64, 0xaa, 0xd9,
	0x81, 0xf0, 0x10, 0x44, 0x6a, 0x30, 0xc5, 0xd6, 0x5d, 0x25, 0xcb, 0xd1, 0x44, 0x40, 0x9b, 0x6d,
	0xd4, 0x7c, 0x00, 0x7d, 0xcd, 0x0e, 0xe9, 0xf0, 0xc8, 0x41, 0x1c, 0x93, 0xd2, 0x5d, 0x28, 0xb6,
	0x9e, 0x99, 0x6d, 0xc3, 0x41, 0x2b, 0xe0, 0xb4, 0x28, 0xe0, 0xfd, 0x4c, 0xb5, 0x1e, 0x6c, 0x0c,
	0x56, 0x7f, 0x66, 0x20, 0xc7, 0xe6, 0xff, 0x8d, 0x8b, 0x23, 0x1f, 0x40, 0x89, 0x53, 0xf5, 0x2e,
	0x3b, 0xa8, 0xe4, 0xab, 0x52, 0x6d, 0x66, 0xab, 0x92, 0x24, 0xbf, 0x79, 0x74, 0xd9, 0x41, 0xad,
	0xc8, 0xec, 0x6c, 0x44, 0x54, 0x28, 0x5e, 0x38, 0xa6, 0xa7, 0x1f, 0xb7, 0x51, 0x29, 0x54, 0xa5,
	0x5a, 0x51, 0xeb, 0xcd, 0x89, 0x02, 0x85, 0x8e, 0x63, 0x76, 0x59, 0xc0, 0x22, 0x5f, 0x0a, 0xa7,
	0x6c, 0xa5, 0x65, 0x5b, 0x1e, 0x5a, 0x9e, 0x52, 0xaa, 0x4a, 0xb5, 0xb2, 0x16, 0x4e, 0xe9, 0x03,
	0xc8, 0x71, 0xbf, 0x25, 0x98, 0x7a, 0x74, 0xf4, 0xd9, 0x8e, 0x26, 0xff, 0x8f, 0x14, 0x20, 0xdb,
	0x78, 0xb4, 0x2d, 0x4b, 0x6c, 0xf0, 0x45, 0x63, 0x57, 0xce, 0xb0, 0xc1, 0xd1, 0x93, 0x23, 0x39,
	0xcb, 0x50, 0x3b, 0x4f, 0xb6, 0x77, 0x1e, 0xca, 0x39, 0x36, 0xdc, 0x3f, 0xf8, 0x74, 0x6f, 0x47,
	0x9e, 0xa2, 0xef, 0x03, 0xd9, 0x66, 0x99, 0x61, 0xc3, 0x31, 0xbb, 0xa8, 0xe1, 0xf3, 0x73, 0x74,
	0x3d, 0x52, 0x81, 0xc2, 0xb9, 0x8b, 0x4e, 0xd3, 0x34, 0x82, 0xb3, 0xcd, 0xb3, 0xe9, 0xbe, 0x41,
	0x5f, 0x4a, 0x30, 0x1f, 0xc3, 0xbb, 0x1d, 0xdb, 0x72, 0x91, 0x9d, 0x9a, 0x13, 0x8c, 0x9b, 0x2d,
	0xdb, 0x40, 0xbe, 0x6d, 0x4a, 0x2b, 0x87, 0xc6, 0x6d, 0xdb, 0x40, 0x72, 0x1b, 0xe4, 0x1e, 0xe8,
	0x0c, 0x5d, 0x57, 0x3f, 0x0d, 0xaf, 0x66, 0x36, 0xb4, 0x1f, 0xf8, 0x66, 0xb2, 0x04, 0x45, 0x83,
	0x05, 0x60, 0x0c, 0xfc, 0x3b, 0x2a, 0xf0, 0xf9, 0xbe, 0x41, 0x9f, 0xc2, 0xdc, 0xe3, 0x4e, 0xdb,
	0xd6, 0x0d, 0x5e, 0x1f, 0x01, 0xe1, 0x0d, 0xc8, 0xb1, 0x63, 0x0e, 0x0a, 0x35, 0xad, 0x90, 0xf8,
	0x3a, 0xa9, 0xc2, 0xb4, 0x81, 0xae, 0x67, 0x5a, 0xfc, 0x2e, 0x03, 0xd7, 0x51, 0x13, 0x7d, 0x01,
	0x24, 0xea, 0x7e, 0x42, 0xf9, 0x55, 0xa0, 0xc0, 0x29, 0xf6, 0xd2, 0xcb, 0xb3, 0xe9, 0xbe, 0x41,
	0xbf, 0x86, 0x05, 0xff, 0x7c, 0x3f, 0xc7, 0x8b, 0x37, 0x90, 0x60, 0x26, 0x99, 0xe0, 0x4b, 0x09,
	0x16, 0x85, 0x10, 0x6f, 0x3b, 0xc9, 0x63, 0xb8, 0xde, 0x67, 0xe0, 0x77, 0x91, 0x37, 0x9e, 0xe6,
	0x2b, 0x09, 0x2a, 0x89, 0x20, 0x6f, 0x3b, 0xd1, 0x7b, 0x30, 0xd7, 0xc0, 0x36, 0x7a, 0x18, 0xbd,
	0xca, 0x78, 0x07, 0x92, 0xc4, 0x0e, 0x44, 0x0d, 0x20, 0xd1, 0x4d, 0x93, 0xe1, 0x4c, 0xf7, 0x60,
	0x4e, 0x43, 0xd6, 0x11, 0xc7, 0xa0, 0x96, 0xd6, 0x50, 0x19, 0xdd, 0xa8, 0xa3, 0x09, 0xd1, 0x3d,
	0x84, 0xd9, 0x03, 0xbb, 0x3b, 0x16, 0xd9, 0xd1, 0x35, 0x72, 0x0c, 0x72, 0xdf, 0xe9, 0x84, 0x88,
	0x7f, 0x0c, 0x95, 0x3d, 0xf4, 0xfc, 0x02, 0xdc, 0xf6, 0x1b, 0xf7, 0x55, 0x0b, 0xe1, 0x37, 0x09,
	0x94, 0xe4, 0xde, 0x09, 0xd5, 0x70, 0xbd, 0xff, 0xcc, 0x64, 0xf9, 0xc7, 0x37, 0xe0, 0xf5, 0xee,
	0xbd, 0x3e, 0x1f, 0xc1, 0x22, 0x23, 0x67, 0xb6, 0x71, 0xcc, 0xb4, 0x7e, 0x91, 0xe0, 0xba, 0xb8,
	0x73, 0x42, 0x49, 0x85, 0xed, 0x24, 0x3b, 0xbc, 0x9d, 0xd0, 0x4f, 0x80, 0x04, 0x8c, 0x98, 0xf0,
	0x09, 0x13, 0xb9, 0x05, 0xb3, 0x8e, 0x6d, 0xa7, 0x28, 0x8d, 0x19, 0x66, 0xee, 0xeb, 0x0c, 0xfa,
	0xb3, 0x04, 0xf3, 0xb1, 0xfd, 0x13, 0x4a, 0xa7, 0x06, 0x39, 0xcf, 0xc1, 0x30, 0x1d, 0x51, 0x8e,
	0x71, 0xd1, 0xa6, 0x71, 0x04, 0xfd, 0x0a, 0x94, 0xc7, 0x1d, 0x26, 0x5f, 0xc6, 0xbf, 0x1f, 0xb2,
	0x0a, 0xd3, 0x16, 0x5e, 0x34, 0xc3, 0x6a, 0xc8, 0x70, 0xd1, 0x01, 0x16, 0x5e, 0x04, 0x7e, 0xe8,
	0x37, 0xb0, 0x94, 0xe2, 0x7c, 0x42, 0xdf, 0xcf, 0x53, 0x90, 0x0f, 0x9f, 0xe9, 0xce, 0x58, 0x5f,
	0xfe, 0x6d, 0x90, 0x03, 0xf9, 0x12, 0x9a, 0x7c, 0x99, 0x5c, 0xd2, 0x66, 0x7d, 0x1d, 0xd3, 0x33,
	0xd3, 0x16, 0xcc, 0x45, 0xdc, 0x4f, 0x28, 0x87, 0x0f, 0x61, 0xbe, 0x61, 0x5f, 0x58, 0xa2, 0x68,
	0x19, 0xf5, 0xa1, 0xfc, 0x2e, 0xc1, 0x42, 0x7c, 0xdf, 0xbf, 0xfb, 0x99, 0x44, 0xa5, 0x68, 0x2e,
	0x26, 0x45, 0xb7, 0xfe, 0x2e, 0xc3, 0x0c, 0x03, 0x1e, 0xe8, 0x96, 0x7e, 0x8a, 0x67, 0x68, 0x79,
	0xe4, 0x12, 0xa6, 0x23, 0x4a, 0x91, 0x54, 0xe3, 0x5e, 0x93, 0xa2, 0x53, 0x7d, 0x67, 0x08, 0xc2,
	0xe7, 0x4b, 0x6f, 0xbe, 0xfa, 0xe3, 0xaf, 0xd7, 0x99, 0x55, 0xaa, 0xd6, 0xf9, 0xcf, 0x02, 0xfe,
	0x3b, 0xaf, 0x7b, 0xb7, 0xce, 0xa5, 0x61, 0x9d, 0x2b, 0x74, 0xbc, 0x2f, 0xdd, 0x21, 0xdf, 0xc2,
	0xb5, 0x98, 0xc2, 0x21, 0x34, 0xcd, 0x75, 0x5c, 0x61, 0xa9, 0x6b, 0x43, 0x31, 0x01, 0x81, 0x75,
	0x4e, 0x60, 0x85, 0x2e, 0xc5, 0x09, 0xb0, 0x49, 0x24, 0xfe, 0xf7, 0x12, 0xcc, 0x0a, 0xda, 0x83,
	0xac, 0x0f, 0x72, 0x1f, 0xd5, 0x3f, 0xea, 0xcd, 0x11, 0xa8, 0x80, 0xc6, 0x06, 0xa7, 0x51, 0xa5,
	0xff, 0x17, 0x68, 0x70, 0x54, 0x84, 0xc8, 0x0f, 0x12, 0xc8, 0xe2, 0x0b, 0x42, 0x84, 0x18, 0x03,
	0x5e, 0x27, 0x75, 0x63, 0x14, 0x2c, 0x7e, 0x24, 0x64, 0x39, 0x9d, 0x4b, 0x10, 0xf4, 0x3b, 0x98,
	0x89, 0xf7, 0x7c, 0xb2, 0x96, 0xf4, 0x9f, 0xe8, 0x55, 0xea, 0xfa, 0x70, 0x50, 0x40, 0x81, 0x72,
	0x0a, 0xcb, 0x44, 0x4d, 0xbb, 0x95, 0x20, 0x9c, 0x07, 0xd3, 0x91, 0x16, 0x2d, 0x96, 0x63, 0xb2,
	0xfb, 0x8b, 0xe5, 0x98, 0xd2, 0xdf, 0x69, 0x95, 0xc7, 0x55, 0x89, 0x92, 0x56, 0x8e, 0xac, 0x0f,
	0x93, 0x1f, 0x25, 0xf6, 0x6b, 0x45, 0xe8, 0x95, 0x44, 0x38, 0xda, 0x41, 0x9d, 0x5a, 0xbd, 0x35,
	0x12, 0x77, 0x85, 0xb2, 0x3c, 0xe7, 0xbb, 0x58, 0x35, 0x9c, 0x03, 0xf4, 0x85, 0x25, 0x59, 0x8d,
	0x3b, 0x4f, 0xe8, 0x54, 0xb5, 0x3a, 0x18, 0x70, 0x85, 0xb0, 0x06, 0x87, 0x07, 0x61, 0xfb, 0x02,
	0x51, 0x0c, 0x9b, 0xd0, 0xa0, 0x62, 0xd8, 0xa4, 0xb6, 0x1c, 0x1a, 0xd6, 0xe1, 0x70, 0x16, 0xd6,
	0x86, 0x62, 0x28, 0xee, 0xc8, 0x8d, 0xb8, 0x4f, 0x41, 0x49, 0x8a, 0x21, 0x93, 0xbf, 0xff, 0xc2,
	0x0a, 0xa3, 0x95, 0x94, 0x90, 0x67, 0x76, 0x37, 0xcc, 0xb3, 0xbf, 0x53, 0xcc, 0x33, 0xf1, 0x93,
	0xf5, 0x0a, 0x41, 0x87, 0xdf, 0x2a, 0x83, 0xb3, 0xb0, 0xcf, 0xa1, 0xd4, 0x7b, 0xc1, 0xc8, 0x4a,
	0xdc, 0xa9, 0xf8, 0x72, 0xaa, 0xab, 0x03, 0xd7, 0x83, 0x98, 0x6b, 0x3c, 0xe6, 0x0d, 0xaa, 0xa4,
	0xc4, 0x74, 0x19, 0x9a, 0x85, 0x7c, 0x01, 0xe5, 0xe8, 0xbb, 0x44, 0x84, 0x4f, 0x25, 0xe5, 0xad,
	0x53, 0xe9, 0x30, 0xc8, 0x88, 0xae, 0xc6, 0xcb, 0x29, 0xd8, 0x70, 0x5f, 0xba, 0xf3, 0x20, 0xf7,
	0x65, 0xa6, 0x73, 0x7c, 0x9c, 0xe7, 0x7f, 0xea, 0xdd, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe9,
	0xc3, 0x81, 0xa2, 0x11, 0x14, 0x00, 0x00,
}
